import mongoose from 'mongoose';

/**
 * A detected trading opportunity surfaced by the Opportunity Scanner.
 * Opportunities are generated by a background job across many symbols, ranked
 * by confidenceScore, and expire after a while so the board stays fresh.
 */

const opportunitySchema = new mongoose.Schema(
  {
    symbol: { type: String, required: true, index: true },
    market: {
      type: String,
      enum: ['forex', 'crypto', 'indices', 'commodities', 'synthetic'],
      required: true,
      index: true,
    },
    timeframe: { type: String, required: true, index: true },
    currentPrice: Number,

    setupType: {
      type: String,
      enum: ['order-block', 'fair-value-gap', 'breaker-block', 'liquidity-sweep', 'trend-continuation', 'reversal'],
      required: true,
    },
    direction: { type: String, enum: ['BUY', 'SELL'], required: true },
    confidenceScore: { type: Number, min: 0, max: 100, required: true, index: true },
    riskLevel: { type: String, enum: ['low', 'medium', 'high'], default: 'medium', index: true },

    entry: Number,
    stopLoss: Number,
    takeProfit1: Number,
    takeProfit2: Number,
    riskRewardRatio: String,

    rationale: String,
    confluences: [String],

    status: {
      type: String,
      enum: ['active', 'expired', 'triggered'],
      default: 'active',
      index: true,
    },
    detectedAt: { type: Date, default: Date.now },
    expiresAt: { type: Date, index: true },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

opportunitySchema.index({ status: 1, confidenceScore: -1 });
opportunitySchema.index({ market: 1, timeframe: 1, confidenceScore: -1 });

// Virtual: whether this opportunity is still fresh.
opportunitySchema.virtual('isActive').get(function () {
  return this.status === 'active' && (!this.expiresAt || this.expiresAt > new Date());
});

const Opportunity = mongoose.model('Opportunity', opportunitySchema);

export default Opportunity;
