import { BaseMarketProvider } from './BaseMarketProvider.js';

/**
 * Deterministic mock market-data provider — the zero-config fallback.
 *
 * Prices are generated by a seeded pseudo-random walk anchored to each symbol's
 * catalog `base` price. "Deterministic" matters: the same symbol+timeframe on
 * the same day yields the same candles, so analyses are stable and reproducible
 * in development. `isRealData` is false so the assistant honestly labels the
 * data as simulated.
 */
export class MockMarketProvider extends BaseMarketProvider {
  constructor(config = {}) {
    super(config);
    this.name = 'mock';
  }

  isConfigured() {
    return true; // always available
  }

  get isRealData() {
    return false;
  }

  // Simple, stable string hash → 32-bit int seed.
  _seed(str) {
    let h = 2166136261;
    for (let i = 0; i < str.length; i += 1) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }

  // Mulberry32 PRNG — fast, seedable, good enough for synthetic candles.
  _rng(seed) {
    let a = seed;
    return () => {
      a |= 0;
      a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  _decimals(price) {
    return price < 10 ? 5 : price < 1000 ? 2 : 1;
  }

  _generate(entry, timeframe, limit) {
    const base = entry.base || 100;
    // Day-stable seed: same candles for a given symbol/timeframe/day.
    const day = new Date().toISOString().slice(0, 10);
    const rand = this._rng(this._seed(`${entry.symbol}|${timeframe}|${day}`));
    const dp = this._decimals(base);

    // Volatility scales with timeframe.
    const vol = { M5: 0.0015, M15: 0.0025, M30: 0.004, H1: 0.006, H4: 0.012, D1: 0.02 }[timeframe] || 0.006;

    const candles = [];
    let price = base * (0.98 + rand() * 0.04); // start within ±2% of base
    const now = Date.now();
    const tfMs =
      { M5: 5, M15: 15, M30: 30, H1: 60, H4: 240, D1: 1440 }[timeframe] * 60 * 1000 || 3600000;

    for (let i = limit - 1; i >= 0; i -= 1) {
      const drift = (rand() - 0.5) * 2 * vol * price;
      const open = price;
      const close = Math.max(0.00001, open + drift);
      const wick = Math.abs(drift) * (0.5 + rand());
      const high = Math.max(open, close) + wick * rand();
      const low = Math.min(open, close) - wick * rand();
      candles.push({
        time: new Date(now - i * tfMs).toISOString(),
        open: Number(open.toFixed(dp)),
        high: Number(high.toFixed(dp)),
        low: Number(low.toFixed(dp)),
        close: Number(close.toFixed(dp)),
        volume: Math.round(1000 + rand() * 9000),
      });
      price = close;
    }
    return candles;
  }

  async getCandles(entry, timeframe = 'H1', limit = 120) {
    return this._generate(entry, timeframe, limit);
  }

  async getQuote(entry) {
    const candles = this._generate(entry, 'H1', 2);
    const last = candles[candles.length - 1];
    return {
      symbol: entry.symbol,
      price: last.close,
      timestamp: last.time,
      source: 'mock',
    };
  }
}
