import PDFDocument from 'pdfkit';

/**
 * Generates export artifacts (PDF for a single analysis, CSV for many).
 * PDF is streamed into a Buffer so the controller can set headers and send it.
 */

const money = (v) => (v === null || v === undefined ? '—' : String(v));

/**
 * Build a professional single-analysis PDF report.
 * @param {Object} analysis - a lean Analysis document
 * @returns {Promise<Buffer>}
 */
export const generateAnalysisPDF = (analysis) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const purple = '#6366f1';
    const dark = '#111827';
    const gray = '#6b7280';

    // Header
    doc.rect(0, 0, doc.page.width, 90).fill(purple);
    doc.fillColor('#ffffff').fontSize(22).text('AI Chart Scanner', 50, 30);
    doc.fontSize(11).text('Institutional-Grade Technical Analysis Report', 50, 60);
    doc.moveDown(3);

    doc.fillColor(dark).fontSize(18).text(`${analysis.symbol} — ${analysis.timeframe}`, 50, 110);
    doc.fillColor(gray).fontSize(10).text(
      `Market: ${analysis.market}   |   Broker: ${analysis.broker}   |   Date: ${new Date(
        analysis.createdAt
      ).toLocaleString()}`
    );
    doc.moveDown(1.5);

    // Decision box
    const decisionColor =
      analysis.decision === 'BUY' ? '#16a34a' : analysis.decision === 'SELL' ? '#dc2626' : '#6b7280';
    doc.roundedRect(50, doc.y, doc.page.width - 100, 60, 8).fill(decisionColor);
    doc.fillColor('#ffffff').fontSize(20).text(analysis.decision.replace('_', ' '), 60, doc.y - 48);
    doc.fontSize(12).text(`Confidence: ${analysis.confidenceScore}%`, doc.page.width - 210, doc.y - 30);
    doc.moveDown(2);

    // Trade plan
    doc.fillColor(dark).fontSize(14).text('Trade Plan', { underline: true });
    doc.moveDown(0.5);
    const tp = analysis.tradePlan || {};
    const rows = [
      ['Entry', money(tp.entry)],
      ['Stop Loss', money(tp.stopLoss)],
      ['Take Profit 1', money(tp.takeProfit1)],
      ['Take Profit 2', money(tp.takeProfit2)],
      ['Take Profit 3', money(tp.takeProfit3)],
      ['Risk/Reward', money(tp.riskRewardRatio)],
      ['Est. Duration', money(tp.estimatedDuration)],
      ['Est. Probability', tp.estimatedProbability != null ? `${tp.estimatedProbability}%` : '—'],
    ];
    doc.fontSize(10).fillColor(gray);
    rows.forEach(([k, v]) => doc.text(`${k}: `, { continued: true }).fillColor(dark).text(v).fillColor(gray));
    doc.moveDown(1);

    // Report
    const rep = analysis.report || {};
    doc.fillColor(dark).fontSize(14).text('Analysis Summary', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor(gray).text(rep.summary || 'No summary available.');
    doc.moveDown(1);

    const listSection = (title, items) => {
      if (!items || items.length === 0) return;
      doc.fillColor(dark).fontSize(12).text(title);
      doc.fontSize(9).fillColor(gray);
      items.forEach((i) => doc.text(`• ${i}`));
      doc.moveDown(0.5);
    };
    listSection('Validation Reasons', rep.validationReasons);
    listSection('Confluences', rep.confluences);
    listSection('Risks', rep.risks);
    listSection('Weaknesses', rep.weaknesses);
    listSection('Missing Elements', rep.missingElements);

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#9ca3af').text(
      'Disclaimer: This analysis is generated by AI for educational purposes only and is not financial advice. Trade at your own risk.',
      { align: 'center' }
    );

    doc.end();
  });

/**
 * Build a CSV string from a list of analyses (for the history export).
 * @param {Array} analyses
 * @returns {string}
 */
export const generateAnalysesCSV = (analyses) => {
  const headers = [
    'Date', 'Symbol', 'Market', 'Timeframe', 'Broker', 'Current Price',
    'Decision', 'Confidence', 'Entry', 'Stop Loss', 'TP1', 'TP2', 'TP3',
    'Risk/Reward', 'Est. Duration', 'Est. Probability',
  ];

  const escape = (val) => {
    const s = val === null || val === undefined ? '' : String(val);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };

  const lines = [headers.join(',')];
  for (const a of analyses) {
    const tp = a.tradePlan || {};
    lines.push(
      [
        new Date(a.createdAt).toISOString(),
        a.symbol, a.market, a.timeframe, a.broker, a.currentPrice,
        a.decision, a.confidenceScore,
        tp.entry, tp.stopLoss, tp.takeProfit1, tp.takeProfit2, tp.takeProfit3,
        tp.riskRewardRatio, tp.estimatedDuration, tp.estimatedProbability,
      ]
        .map(escape)
        .join(',')
    );
  }
  return lines.join('\n');
};
